export const AuthRouteEnum = {
  ROOT: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  LOGOUT: "/logout",
  OTP_VERIFICATION: "/otp-verification",
  FORGOT_PASSWORD: "/forgot",
  RESET_PASSWORD: "/reset-password",
  CHANGE_PASSWORD: "/change-password",
  EDIT_PROFILE: "/edit-profile",
};

export const AppRouteEnum = {
  INDEX: "/",
  HOME: "/home",
  ACCOUNT: {
    INDEX: "/account",
    EDIT_PROFILE: "/account/edit-profile",
    CHANGE_PASSWORD: "/account/change-password",
    WALLET: "/account/wallet",
    OFFERS: "/account/offers",
    ORDERS: "/account/orders",
    ORDER_DETAILS: "/account/orders/[id]",
    ORDER_TRACK: "/account/orders/[id]/track",
    ORDER_INVOICE: "/account/orders/[id]/invoice",
    PRESCRIPTIONS: "/account/prescriptions",
    PRESCRIPTION_DETAILS: "/account/prescriptions/[id]",
    PRESCRIPTION_INVOICE: "/account/prescriptions/[id]/invoice",
    NOTIFICATIONS: "/account/notifications",
    ADDRESSES: "/account/addresses",
    ADD_ADDRESS: "/account/addresses/add-address",
    EDIT_ADDRESS: "/account/addresses/edit/[id]",
    HELP: "/account/help",
    PRIVACY_POLICY: "/account/privacy-policy",
    TERMS_OF_USE: "/account/terms-of-use",
    SETTINGS: "/account/settings",
  },
  APPOINTMENT: {
    INDEX: "/appointment",
    BOOK_AN_APPOINTMENT: "/appointment/book-an-appointment",
  },
  CAB: { INDEX: "/cab", BOOK_CAB: "/cab/book-cab" },
  CART: { INDEX: "/cart" },
  CHECKOUT: {
    INDEX: "/checkout",
    PAYMENT: "/checkout/payment",
    ORDER_SUMMARY: "/checkout/order-summary",
  },
  INSURANCE: {
    INDEX: "/insurance",
    GET_QUOTES: "/insurance/get-quotes",
    SUBMIT_ENQUIRY: "/insurance/submit-enquiry",
  },
  NOTIFICATIONS: { INDEX: "/notifications" },
  PATHOLOGY: {
    INDEX: "/pathology",
    BOOK_TEST: "/pathology/book-test",
    BOOK_TEST_DETAILS: "/pathology/book-test/[id]",
    BOOK_TEST_TRACK: "/pathology/book-test/[id]/track",
    BOOK_TEST_INVOICE: "/pathology/book-test/[id]/invoice",
  },
  PHARMACY: {
    INDEX: "/pharmacy",
    ORDER_MEDICINE: "/pharmacy/order-medicine",
    ORDER_MEDICINE_DETAILS: "/pharmacy/order-medicine/[id]",
    ORDER_MEDICINE_TRACK: "/pharmacy/order-medicine/[id]/track",
    ORDER_MEDICINE_INVOICE: "/pharmacy/order-medicine/[id]/invoice",
  },
  SEARCH: { INDEX: "/search" },
  SELECT_LOCATION: { INDEX: "/select-location" },
};